# Generated by Django 5.2.4 on 2025-09-04 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0002_remove_book_genre_remove_book_published_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
